=== 5634224/2-DAW/Materias/LMSGI/Evaluacion 2/Tema 4/Recursos/Actividades/Actividad 4/Soluciones/LMSGI04A4.dtd
<!ELEMENT comunidad (propietarios, propiedades, cuotas, derramas?)>
<!ATTLIST comunidad fecha_actualizacion CDATA #REQUIRED>

<!ELEMENT propietarios (propietario+)>

<!ELEMENT propietario ANY>
<!ATTLIST propietario
    id ID #REQUIRED
    apellidos CDATA #REQUIRED
    nombre CDATA #REQUIRED
    alcorriente CDATA #IMPLIED
>

<!ELEMENT propiedades (propiedad+)>
<!ELEMENT propiedad (participacion+)>
<!ATTLIST propiedad
    id ID #REQUIRED
    tipo IDREF #REQUIRED
    contacto CDATA #IMPLIED
>

<!ELEMENT participacion ANY>
<!ATTLIST participacion
    propietario IDREF #REQUIRED
    porcentaje CDATA #REQUIRED
>
<!ELEMENT cuotas (cuota*)>
<!ELEMENT cuota ANY>
<!ATTLIST cuota
    tipo ID #REQUIRED
    valor CDATA #REQUIRED
>

<!ELEMENT derramas (derrama*)>
<!ELEMENT derrama ANY>
<!ATTLIST derrama
    id ID #REQUIRED
    valor CDATA #REQUIRED
    asunto CDATA #REQUIRED
    desde CDATA #REQUIRED
    hasta CDATA #REQUIRED
>

<!ATTLIST comunidad fecha_actualizacion CDATA #REQUIRED>
<!ATTLIST comunidad fecha_actualizacion CDATA #REQUIRED>
<!ATTLIST comunidad fecha_actualizacion CDATA #REQUIRED>

=== 5634224/2-DAW/Materias/LMSGI/Evaluacion 2/Tema 4/Recursos/Actividades/Actividad 4/Soluciones/LMSGI04A4-xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE comunidad SYSTEM "LMSGI04A4.dtd"> -->
<!DOCTYPE comunidad>
<comunidad 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="./LMSGI04A4.xsd"
	fecha_actualizacion="2020-01-20T08:00:00">
	
	<propietarios>
		<propietario id="JMMM" apellidos="Mendoza Martínez" nombre="José Manuel" alcorriente="true" />
		<propietario id="AFGL" apellidos="Gálvez Lorente" nombre="Ana Francisca" alcorriente="true" />
		<propietario id="CNAA" apellidos="Casas Nuevas" nombre="Alfredo Arturo" alcorriente="true" />
		<propietario id="CEGL" apellidos="Gómez López" nombre="Cristina Elena" alcorriente="true" />
		<propietario id="GRNC" apellidos="Navas Conesa" nombre="Gregorio Rodrigo" />
		<propietario id="IPUL" apellidos="Usillos Liarte" nombre="Ignacio Patricio" />
	</propietarios>
	<propiedades>
		<propiedad id="C01" tipo="vivienda120" contacto="CNAA">
			<participacion propietario="CNAA" porcentaje="50" />
			<participacion propietario="AFGL" porcentaje="50" />
		</propiedad>
		<propiedad id="C02" tipo="vivienda90">
			<participacion propietario="GRNC" porcentaje="100" />
		</propiedad>
		<propiedad id="C03" tipo="vivienda90" contacto="CEGL">
			<participacion propietario="IPUL" porcentaje="50" />
			<participacion propietario="CEGL" porcentaje="50" />
		</propiedad>
		<propiedad id="C04" tipo="vivienda150">
			<participacion propietario="JMMM" porcentaje="100" />
		</propiedad>
		<propiedad id="G01" tipo="garaje" contacto="CNAA">
			<participacion propietario="CNAA" porcentaje="50" />
			<participacion propietario="AFGL" porcentaje="50" />
		</propiedad>
		<propiedad id="G02" tipo="garaje">
			<participacion propietario="JMMM" porcentaje="100" />
		</propiedad>
	</propiedades>
	<cuotas>
		<cuota tipo="vivienda90" valor="35.0" />
		<cuota tipo="vivienda120" valor="45.0" />
		<cuota tipo="vivienda150" valor="50.0" />
		<cuota tipo="garaje" valor="15.0" />
	</cuotas>
	<derramas>
		<derrama id="D001" valor="20.0" asunto="Arreglos fachada" desde="2019-10-01" hasta="2020-09-01">
		Se ha procedido a restaurar la fachada completa, usando mortero monocapa,
		según acuerdo de junta ordinaria de la fecha 15/07/2019.
		</derrama>
	</derramas>
</comunidad>
