=== 5634224/2-DAW/Materias/LMSGI/Evaluacion 2/Tema 4/Tarea/Realización/LMSGI04.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="catalogo">
        <xs:complexType>
            <!-- Hijos -->
            <xs:sequence>

                <xs:element name="elenco">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="miembro" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <!-- Atributos -->
                                    <xs:attribute name="id" type="xs:ID" use="required" />
                                    <xs:attribute name="rol_principal" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="director"></xs:enumeration>
                                                <xs:enumeration value="actriz"></xs:enumeration>
                                                <xs:enumeration value="actor"></xs:enumeration>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="nombre" type="xs:string" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="planes">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="plan" maxOccurs="unbounded">
                                <xs:complexType>
                                    <!-- Atributos -->
                                    <xs:attribute name="id" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:ID">
                                                <xs:pattern value="P[1-9]" />
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="nombre" type="xs:string" use="required" />
                                    <xs:attribute name="mensualidad" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:decimal">
                                                <xs:minInclusive value="0"></xs:minInclusive>
                                                <xs:fractionDigits value="2"></xs:fractionDigits>
                                                <xs:totalDigits value="5"></xs:totalDigits>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="titulos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="genero" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="titulo" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <!-- Hijos -->
                                                <xs:sequence>
                                                    <xs:element name="reparto" minOccurs="0" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:attribute name="miembro" type="xs:IDREF" use="required" />
                                                            <xs:attribute name="rol">
                                                                <xs:simpleType>
                                                                    <xs:restriction base="xs:string">
                                                                        <xs:enumeration value="protagonista"></xs:enumeration>
                                                                    </xs:restriction>
                                                                </xs:simpleType>
                                                            </xs:attribute>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="sinopsis" type="xs:string" minOccurs="0" />
                                                </xs:sequence>

                                                <!-- Atributos -->
                                                <xs:attribute name="nombre" type="xs:string" use="required" />
                                                <xs:attribute name="anyo" type="xs:gYear" use="required" />
                                                <xs:attribute name="duracion" use="required">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:integer">
                                                            <xs:minInclusive value="10"></xs:minInclusive>
                                                            <xs:maxInclusive value="1000"></xs:maxInclusive>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:attribute>
                                                <xs:attribute name="alquiler">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:decimal">
                                                            <xs:minInclusive value="0"></xs:minInclusive>
                                                            <xs:fractionDigits value="2"></xs:fractionDigits>
                                                            <xs:totalDigits value="5"></xs:totalDigits>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:attribute>
                                                <xs:attribute name="compra">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:decimal">
                                                            <xs:minInclusive value="0"></xs:minInclusive>
                                                            <xs:fractionDigits value="2"></xs:fractionDigits>
                                                            <xs:totalDigits value="5"></xs:totalDigits>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:attribute>
                                                <xs:attribute name="plan" type="xs:IDREF" />
                                                <xs:attribute name="nrm">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:integer">
                                                            <xs:enumeration value="7"></xs:enumeration>    
                                                            <xs:enumeration value="12"></xs:enumeration>
                                                            <xs:enumeration value="16"></xs:enumeration>
                                                            <xs:enumeration value="18"></xs:enumeration>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>

                                    <!-- Atributos -->
                                    <xs:attribute name="nombre" type="xs:ID" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>

            <!-- Atributos -->
            <xs:attribute name="inicio" type="xs:date" use="required" />
            <xs:attribute name="vigencia" type="xs:date" use="required" />
            
        </xs:complexType>
    </xs:element>
</xs:schema>

=== 5634224/2-DAW/Materias/LMSGI/Evaluacion 2/Tema 4/Tarea/Realización/LMSGI04-xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<catalogo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./LMSGI04.xsd"
    inicio="2023-01-01" vigencia="2023-01-31">
    <elenco>
        <miembro id="PN1" rol_principal="director" nombre="Peter Nolan" />
        <miembro id="SH1" rol_principal="director" nombre="Steven Hawking" />
        <miembro id="CC1" rol_principal="actriz" nombre="Cindy Crowe" />
        <miembro id="HS1" rol_principal="actor" nombre="Harrison Seat" />
        <miembro id="RT1" rol_principal="actriz" nombre="Ruby Thompson" />
        <miembro id="JR1" rol_principal="actor" nombre="Jason Renner" />
        <miembro id="AR1" rol_principal="actriz" nombre="Anya Ramirez" />
        <miembro id="JS1" rol_principal="actor" nombre="Jeremy Statham" />
    </elenco>
    <planes>
        <plan id="P1" nombre="básico" mensualidad="9.99" />
        <plan id="P2" nombre="avanzado" mensualidad="19.99" />
        <plan id="P3" nombre="premium" mensualidad="29.99" />
    </planes>
    <titulos>
        <genero nombre="Acción">
            <titulo nombre="Pesadilla después de Navidad" anyo="1998" duracion="116" alquiler="4.50" compra="14.90" plan="P2">
                <reparto miembro="PN1" />
                <reparto miembro="CC1" rol="protagonista" />    
                <reparto miembro="JR1" />
                <reparto miembro="RT1" />
                <sinopsis>
                    Tras las vacaciones navideñas, una familia de clase media decide iniciar una dieta.    
                </sinopsis>
            </titulo>
            <titulo nombre="The Rooom" anyo="2003" duracion="124" alquiler="4.50" plan="P2">
                <reparto miembro="SH1" />
                <reparto miembro="RT1" rol="protagonista" />
                <reparto miembro="HS1" />
            </titulo>
            <titulo nombre="Inquilinos cibernéticos" anyo="1995" duracion="107" alquiler="4.50" compra="14.90" plan="P2" nrm="12">
                <reparto miembro="PN1" />
                <reparto miembro="HS1" rol="protagonista" />
                <reparto miembro="JR1" />
                <sinopsis>
                    Se encuentran hospedados en el lugar más inhóspito del mundo.
                </sinopsis>
            </titulo>
            <titulo nombre="Huye, brigada espacial" anyo="1984" duracion="184" alquiler="3.50" compra="9.90" plan="P1">
                <reparto miembro="SH1" />
                <reparto miembro="JR1" rol="protagonista" />    
                <reparto miembro="HS1" />
                <reparto miembro="RT1" />
            </titulo>
            <titulo nombre="Se acabó el juguete" anyo="2007" duracion="130" alquiler="4.50" compra="14.90" plan="P2">
                <reparto miembro="SH1" />
                <reparto miembro="JR1" rol="protagonista" />    
            </titulo>
            <titulo nombre="Efectos letales" anyo="2001" duracion="155" alquiler="4.50" plan="P2">
                <reparto miembro="SH1" />
                <reparto miembro="JS1" rol="protagonista" />    
                <reparto miembro="JR1" />
                <sinopsis>
                    Todo sucede antes de que te des cuenta.
                </sinopsis>
            </titulo>
            <titulo nombre="Noches de mil gritos" anyo="2009" duracion="204" compra="39.90" nrm="7">
                <reparto miembro="PN1" />
                <reparto miembro="HS1" rol="protagonista" />    
                <reparto miembro="RT1" />
                <sinopsis>
                    Ten los tapones para los oidos cerca.    
                </sinopsis>
            </titulo>
        </genero>
        <genero nombre="Terror">
            <titulo nombre="Demonis" anyo="2004" duracion="98" alquiler="3.50" compra="9.90" plan="P1" nrm="18">
                <reparto miembro="PN1" />
                <reparto miembro="CC1" rol="protagonista" />    
                <reparto miembro="AR1" />
            </titulo>
            <titulo nombre="Funda sangrienta" anyo="1992" duracion="114" alquiler="3.50" compra="9.90" plan="P1" nrm="16">
                <reparto miembro="PN1" />
                <reparto miembro="RT1" rol="protagonista" />    
                <reparto miembro="HS1" />
            </titulo>
            <titulo nombre="Máquina mortal" anyo="1991" duracion="129" compra="14.90" plan="P2" nrm="18">
                <reparto miembro="SH1" />
                <reparto miembro="HS1" rol="protagonista" />    
                <reparto miembro="RT1" />
                <sinopsis>
                    Ha sido entrenado para este momento durante toda su vida.    
                </sinopsis>
            </titulo>
            <titulo nombre="Curso del 89" anyo="1989" duracion="90" alquiler="4.50" compra="14.90" plan="P2" nrm="18">
                <reparto miembro="PN1" />
                <reparto miembro="RT1" rol="protagonista" />    
                <reparto miembro="JR1" />
                <reparto miembro="HS1" />
                <reparto miembro="JS1" />
                <sinopsis>
                    La venganza del no promocionado no se hace esperar.
                </sinopsis>
            </titulo>
            <titulo nombre="La partida de los vivos murientes" anyo="1978" duracion="164" compra="39.90" nrm="18">
                <reparto miembro="SH1" />
                <reparto miembro="JS1" rol="protagonista" />    
                <reparto miembro="JR1" />
                <reparto miembro="AR1" />
                <sinopsis>
                    Solo pueden quedar dos, porque juegan por parejas.                
                </sinopsis>
            </titulo>
        </genero>
        <genero nombre="Comedia">            
            <titulo nombre="Juego letal" anyo="2014" duracion="112" alquiler="5.50" compra="29.90" plan="P3" nrm="12">
                <reparto miembro="PN1" />
                <reparto miembro="AR1" rol="protagonista" />    
                <reparto miembro="JR1" />
            </titulo>
            <titulo nombre="El brujo Lockwar" anyo="1997" duracion="106" alquiler="4.50" compra="14.90" plan="P2" nrm="12">
                <reparto miembro="SH1" />
                <reparto miembro="RT1" rol="protagonista" />    
                <reparto miembro="JR1" />
            </titulo>
            <titulo nombre="Masterwish" anyo="1990" duracion="185" alquiler="5.50" compra="29.90" plan="P3">
                <reparto miembro="PN1" />
                <reparto miembro="RT1" rol="protagonista" />    
                <reparto miembro="JR1" />
                <reparto miembro="JS1" />
                <sinopsis>
                    El rey de los deseos desea complacerte.
                </sinopsis>
            </titulo>
            <titulo nombre="La alucinante pandilla" anyo="2003" duracion="142" alquiler="3.50" compra="9.90" plan="P1">
                <reparto miembro="SH1" />
                <reparto miembro="JS1" rol="protagonista" />    
                <reparto miembro="AR1" />
            </titulo>
            <titulo nombre="Razas de día" anyo="1997" duracion="150" alquiler="4.50" plan="P2" nrm="7">
                <reparto miembro="SH1" />
                <reparto miembro="RT1" rol="protagonista" />    
                <reparto miembro="HS1" />
            </titulo>
            <titulo nombre="Calles de hielo" anyo="2012" duracion="112" alquiler="3.50" compra="9.90" plan="P1">
                <reparto miembro="SH1" />
                <reparto miembro="AR1" rol="protagonista" />    
                <reparto miembro="JR1" />
                <sinopsis>
                    La vida en la ciudad es difícil para un grupo de adolescentes.
                </sinopsis>
            </titulo>
            <titulo nombre="El señor de las pulseras" anyo="2000" duracion="212" compra="39.90">
                <reparto miembro="PN1" />
                <reparto miembro="AR1" rol="protagonista" />    
                <reparto miembro="JS1" />
                <sinopsis>
                    El nuevo hijo nonato del rey vende sus creaciones en el mercado ambulante.
                </sinopsis>
            </titulo>
        </genero>
    </titulos>
</catalogo>
